# -*- coding: utf-8 -*-
"""Seasonal_Agriculture_Performance_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EN09KDzjJIrpZCTCnOI-j5shHpjhnJav
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("seasonal_agriculture_performance_dataset.csv")

print("Dataset loaded successfully!")

df.head()

df.info()
df.describe()

missing_values = df.isnull().sum()

missing_values = missing_values[missing_values > 0]

print(missing_values)

duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

print("Seasons:")
print(df["Season"].value_counts())

print("\nCrops:")
print(df["Crop"].value_counts())

print("\nIrrigation Methods:")
print(df["Irrigation_Method"].value_counts())

print("Number of unique states:", df["State"].nunique())
print("Number of unique districts:", df["District"].nunique())

print("\nStates:")
print(df["State"].value_counts())

print("\nDistricts:")
print(df["District"].value_counts())

# Check whether Farm IDs are unique

print("Total Farm IDs:", df["Farm_ID"].nunique())
print("Total Records:", len(df))

if df["Farm_ID"].nunique() == len(df):
    print("Every farm has a unique ID.")
else:
    print("Some Farm IDs are repeated.")

"""Data Cleaning and Preparation

"""

# Create a copy of the original dataset
df_clean = df.copy()

print("Original dataset shape:", df.shape)
print("Working dataset shape:", df_clean.shape)
df_clean

# Check whether Farm IDs are unique

print("Total Farm IDs:", df["Farm_ID"].nunique())
print("Total Records:", len(df))

if df["Farm_ID"].nunique() == len(df):
    print("Every farm has a unique ID.")
else:
    print("Some Farm IDs are repeated.")

# Create a copy of the original dataset
df_clean = df.copy()

print("Original dataset shape:", df.shape)
print("Cleaned dataset shape:", df_clean.shape)
df_clean

# Check missing values by season

missing_by_season = df_clean.groupby("Season")[
    ["Rainfall_mm", "Soil_Moisture_pct", "Yield_Tonnes_Ha"]
].apply(lambda x: x.isnull().sum())

missing_by_season

# Check missing values by crop

missing_by_crop = df_clean.groupby("Crop")[
    ["Rainfall_mm", "Soil_Moisture_pct", "Yield_Tonnes_Ha"]
].apply(lambda x: x.isnull().sum())

missing_by_crop

# Fill missing numerical values using Season + Crop group medians

columns_to_fill = [
    "Rainfall_mm",
    "Soil_Moisture_pct",
    "Yield_Tonnes_Ha"
]

for column in columns_to_fill:
    df_clean[column] = df_clean[column].fillna(
        df_clean.groupby(["Season", "Crop"])[column].transform("median")
    )

print("Missing values after group-wise imputation:")
print(df_clean[columns_to_fill].isnull().sum())

# Verify the cleaned dataset

print("Rows and columns:", df_clean.shape)
print("Total missing values:", df_clean.isnull().sum().sum())
print("Total duplicate rows:", df_clean.duplicated().sum())

# Check for potentially invalid values

print("Humidity outside 0-100%:",
      ((df_clean["Humidity_pct"] < 0) | (df_clean["Humidity_pct"] > 100)).sum())

print("Soil moisture outside 0-100%:",
      ((df_clean["Soil_Moisture_pct"] < 0) | (df_clean["Soil_Moisture_pct"] > 100)).sum())

print("Disease/Pest risk outside 0-100%:",
      ((df_clean["Disease_Pest_Risk_pct"] < 0) | (df_clean["Disease_Pest_Risk_pct"] > 100)).sum())

print("Negative farm area:",
      (df_clean["Farm_Area_Hectares"] < 0).sum())

print("Negative rainfall:",
      (df_clean["Rainfall_mm"] < 0).sum())

print("Negative production:",
      (df_clean["Production_Tonnes"] < 0).sum())

print("Negative water usage:",
      (df_clean["Water_Used_m3"] < 0).sum())

print("Soil pH outside 0-14:",
      ((df_clean["Soil_pH"] < 0) | (df_clean["Soil_pH"] > 14)).sum())

# Identify potential outliers using the IQR method

outlier_columns = [
    "Farm_Area_Hectares",
    "Rainfall_mm",
    "Yield_Tonnes_Ha",
    "Production_Tonnes",
    "Profit_INR",
    "Water_Used_m3"
]

for column in outlier_columns:
    Q1 = df_clean[column].quantile(0.25)
    Q3 = df_clean[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = ((df_clean[column] < lower_bound) |
                (df_clean[column] > upper_bound)).sum()

    print(f"{column}: {outliers} potential outliers")

# Calculate IQR boundaries for important variables

for column in [
    "Yield_Tonnes_Ha",
    "Production_Tonnes",
    "Profit_INR",
    "Water_Used_m3"
]:

    Q1 = df_clean[column].quantile(0.25)
    Q3 = df_clean[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    print(f"\n{column}")
    print("Q1:", round(Q1, 2))
    print("Q3:", round(Q3, 2))
    print("IQR:", round(IQR, 2))
    print("Lower bound:", round(lower_bound, 2))
    print("Upper bound:", round(upper_bound, 2))

# Identify high-yield observations using the IQR upper bound

Q1 = df_clean["Yield_Tonnes_Ha"].quantile(0.25)
Q3 = df_clean["Yield_Tonnes_Ha"].quantile(0.75)
IQR = Q3 - Q1

upper_yield_limit = Q3 + 1.5 * IQR

high_yield = df_clean[
    df_clean["Yield_Tonnes_Ha"] > upper_yield_limit
]

print("IQR upper limit for Yield:", round(upper_yield_limit, 2))
print("Number of high-yield observations:", len(high_yield))

print("\nHigh-yield observations by Season:")
print(high_yield["Season"].value_counts())

print("\nHigh-yield observations by Crop:")
print(high_yield["Crop"].value_counts())

# Compare yield statistics across crops

crop_yield_stats = df_clean.groupby("Crop")["Yield_Tonnes_Ha"].agg(
    ["count", "mean", "median", "min", "max"]
).round(2)

crop_yield_stats.sort_values("mean", ascending=False)

"""### Yield Distribution Across Crops"""

# Boxplot of yield across crops

plt.figure(figsize=(12, 6))

sns.boxplot(
    data=df_clean,
    x="Crop",
    y="Yield_Tonnes_Ha"
)

plt.title("Yield Distribution Across Crops")
plt.xlabel("Crop")
plt.ylabel("Yield (Tonnes per Hectare)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""## Seasonal Agricultural Performance Analysis"""

# Compare agricultural performance across seasons

season_summary = df_clean.groupby("Season")[
    ["Yield_Tonnes_Ha",
     "Production_Tonnes",
     "Total_Cost_INR",
     "Revenue_INR",
     "Profit_INR",
     "Water_Used_m3",
     "Water_Efficiency_t_per_1000m3"]
].agg(["mean", "median"]).round(2)

season_summary

# Compare average yield across seasons

season_yield = df_clean.groupby("Season")["Yield_Tonnes_Ha"].mean()

plt.figure(figsize=(8, 5))

season_yield.plot(kind="bar")

plt.title("Average Yield Across Seasons")
plt.xlabel("Season")
plt.ylabel("Average Yield (Tonnes per Hectare)")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# Compare average profit across seasons

season_profit = df_clean.groupby("Season")["Profit_INR"].mean()

plt.figure(figsize=(8, 5))

season_profit.plot(kind="bar")

plt.title("Average Profit Across Seasons")
plt.xlabel("Season")
plt.ylabel("Average Profit (INR)")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# Compare average profit across crops

crop_profit = df_clean.groupby("Crop")["Profit_INR"].mean().sort_values(ascending=False)

print("Average Profit by Crop:")
print(crop_profit.round(2))

plt.figure(figsize=(10, 5))

crop_profit.plot(kind="bar")

plt.title("Average Profit Across Crops")
plt.xlabel("Crop")
plt.ylabel("Average Profit (INR)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Check relationship between rainfall and crop yield

plt.figure(figsize=(8, 5))

plt.scatter(
    df_clean["Rainfall_mm"],
    df_clean["Yield_Tonnes_Ha"]
)

plt.title("Rainfall vs Crop Yield")
plt.xlabel("Rainfall (mm)")
plt.ylabel("Yield (Tonnes per Hectare)")

plt.tight_layout()
plt.show()


# Calculate correlation between rainfall and yield

correlation = df_clean["Rainfall_mm"].corr(
    df_clean["Yield_Tonnes_Ha"]
)

print("Correlation between Rainfall and Yield:", round(correlation, 3))

# Calculate correlation between temperature and yield

correlation_temp = df_clean["Avg_Temperature_C"].corr(
    df_clean["Yield_Tonnes_Ha"]
)

print(
    "Correlation between Temperature and Yield:",
    round(correlation_temp, 3)
)


# Calculate correlation between soil moisture and yield

correlation_moisture = df_clean["Soil_Moisture_pct"].corr(
    df_clean["Yield_Tonnes_Ha"]
)

print(
    "Correlation between Soil Moisture and Yield:",
    round(correlation_moisture, 3)
)

# Correlation heatmap of numerical variables

import matplotlib.pyplot as plt
import seaborn as sns

# Select numerical columns
numeric_df = df_clean.select_dtypes(include="number")

# Calculate correlation matrix
correlation_matrix = numeric_df.corr()

# Plot heatmap
plt.figure(figsize=(14, 10))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".2f",
    center=0
)

plt.title("Correlation Heatmap of Agricultural Variables")
plt.tight_layout()
plt.show()

# Find variables most strongly correlated with Yield

yield_correlations = correlation_matrix["Yield_Tonnes_Ha"].sort_values(
    ascending=False
)

print("Correlation with Yield:")
print(yield_correlations)

# Compare average yield by Crop and Season

crop_season_yield = df_clean.groupby(
    ["Crop", "Season"]
)["Yield_Tonnes_Ha"].mean().round(2)

print("Average Yield by Crop and Season:")
print(crop_season_yield)

# Visualize average yield by crop and season

yield_pivot = df_clean.pivot_table(
    index="Crop",
    columns="Season",
    values="Yield_Tonnes_Ha",
    aggfunc="mean"
)

yield_pivot.plot(kind="bar", figsize=(12, 6))

plt.title("Average Crop Yield Across Seasons")
plt.xlabel("Crop")
plt.ylabel("Average Yield (Tonnes per Hectare)")
plt.xticks(rotation=45)
plt.legend(title="Season")
plt.tight_layout()
plt.show()

# Compare average production across seasons

production_by_season = df_clean.groupby("Season")[
    "Production_Tonnes"
].mean().round(2)

print("Average Production by Season:")
print(production_by_season)

# Visualize average production across seasons

plt.figure(figsize=(8, 5))

plt.bar(
    production_by_season.index,
    production_by_season.values
)

plt.title("Average Production Across Seasons")
plt.xlabel("Season")
plt.ylabel("Average Production (Tonnes)")

plt.tight_layout()
plt.show()

# Compare average profit across crops

profit_by_crop = df_clean.groupby("Crop")[
    "Profit_INR"
].mean().sort_values(ascending=False).round(2)

print("Average Profit by Crop:")
print(profit_by_crop)

# Plot average profit across crops

profit_by_crop.plot(kind="bar", figsize=(10, 5))

plt.title("Average Profit Across Crops")
plt.xlabel("Crop")
plt.ylabel("Average Profit (INR)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Compare average revenue across crops

revenue_by_crop = df_clean.groupby("Crop")[
    "Revenue_INR"
].mean().sort_values(ascending=False).round(2)

print("Average Revenue by Crop:")
print(revenue_by_crop)

# Plot average revenue across crops

revenue_by_crop.plot(kind="bar", figsize=(10, 5))

plt.title("Average Revenue Across Crops")
plt.xlabel("Crop")
plt.ylabel("Average Revenue (INR)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Compare average revenue across seasons

revenue_by_season = df_clean.groupby("Season")[
    "Revenue_INR"
].mean().sort_values(ascending=False).round(2)

print("Average Revenue by Season:")
print(revenue_by_season)

# Plot average revenue across seasons

revenue_by_season.plot(kind="bar", figsize=(8, 5))

plt.title("Average Revenue Across Seasons")
plt.xlabel("Season")
plt.ylabel("Average Revenue (INR)")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# Compare average profit across seasons

profit_by_season = df_clean.groupby("Season")[
    "Profit_INR"
].mean().sort_values(ascending=False).round(2)

print("Average Profit by Season:")
print(profit_by_season)

# Plot average profit across seasons

profit_by_season.plot(kind="bar", figsize=(8, 5))

plt.title("Average Profit Across Seasons")
plt.xlabel("Season")
plt.ylabel("Average Profit (INR)")
plt.xticks(rotation=0)
plt.axhline(0, linewidth=1)
plt.tight_layout()
plt.show()

# Compare average profit by crop and season

profit_crop_season = df_clean.groupby(["Crop", "Season"])["Profit_INR"].mean().round(2)

print("Average Profit by Crop and Season:")
print(profit_crop_season)

# Plot average profit by crop and season

profit_table = profit_crop_season.unstack()

profit_table.plot(kind="bar", figsize=(10, 6))

plt.title("Average Profit by Crop and Season")
plt.xlabel("Crop")
plt.ylabel("Average Profit (INR)")
plt.xticks(rotation=45)
plt.legend(title="Season")
plt.tight_layout()
plt.show()

# Find the most and least profitable crop-season combinations

highest_profit = profit_crop_season.idxmax()
highest_value = profit_crop_season.max()

lowest_profit = profit_crop_season.idxmin()
lowest_value = profit_crop_season.min()

print("Most Profitable Crop-Season Combination:")
print(highest_profit, ":", round(highest_value, 2), "INR")

print("\nLeast Profitable Crop-Season Combination:")
print(lowest_profit, ":", round(lowest_value, 2), "INR")

# Final data-driven insights

print("FINAL DATA-DRIVEN INSIGHTS")
print("--------------------------")

print("1. Kharif season has the highest average production and revenue.")
print("2. Sugarcane has the highest average yield and revenue among the crops.")
print("3. Sugarcane in Kharif has the highest profit.")
print("4. Rice in Zaid has the lowest profit.")
print("5. Rainfall, temperature and soil moisture show very weak correlation with yield.")
print("6. Crop and season combinations have a strong effect on profitability.")

